"""add raw_materials and supplier_materials tables

Revision ID: 86ce9e49211f
Revises: 2cec589cb8e6
Create Date: 2025-11-04 10:34:34.957939

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86ce9e49211f'
down_revision: Union[str, Sequence[str], None] = '2cec589cb8e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
